/**
 * 990 Mapper - Export Module
 * Handles CSV export, Excel export, and print view generation.
 */
const Exporter = {

  /**
   * Format a number as currency string with $ and commas.
   */
  _formatCurrency(amount) {
    if (amount == null || isNaN(amount)) return '$0.00';
    return '$' + Number(amount).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  },

  /**
   * Get today's date formatted for filenames (YYYY-MM-DD).
   */
  _fileDate() {
    const d = new Date();
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const dd = String(d.getDate()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd}`;
  },

  /**
   * Get today's date formatted for display (Month Day, Year).
   */
  _displayDate() {
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    const d = new Date();
    return `${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
  },

  /**
   * Escape a value for CSV: wrap in double quotes, escape internal quotes.
   */
  _csvEscape(value) {
    if (value == null) return '""';
    let str = String(value);
    // Prevent CSV formula injection - prefix dangerous leading characters
    if (/^[=+\-@\t\r]/.test(str)) {
      str = "'" + str;
    }
    return '"' + str.replace(/"/g, '""') + '"';
  },

  /**
   * Trigger a file download in the browser using Blob + anchor click.
   */
  _triggerDownload(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  /**
   * Generate and download a CSV file with Part IX mapping data.
   */
  generateCSV(summaryData, mappingResults) {
    const lines = [];
    const date = this._displayDate();

    // Header rows
    lines.push(this._csvEscape(`Form 990 Part IX Mapping - Generated by 990 Mapper (szubair22.github.io/990Mapper) - ${date}`));
    lines.push(this._csvEscape('This is a mapping aid, not tax advice. Consult a qualified tax professional.'));
    lines.push('');

    // Column headers
    lines.push([
      this._csvEscape('Line Number'),
      this._csvEscape('Line Description'),
      this._csvEscape('Total Amount'),
      this._csvEscape('Number of Accounts'),
      this._csvEscape('Mapped Account Names')
    ].join(','));

    // Data rows
    if (summaryData && summaryData.lines) {
      summaryData.lines.forEach(function(item) {
        const accountNames = (item.accounts && item.accounts.length > 0)
          ? item.accounts.map(function(a) { return a.accountName; }).join('; ')
          : '';
        const count = (item.count != null && item.count > 0) ? String(item.count) : '';
        const total = (item.total != null) ? Exporter._formatCurrency(item.total) : '$0.00';

        lines.push([
          Exporter._csvEscape(item.line),
          Exporter._csvEscape(item.label),
          Exporter._csvEscape(total),
          Exporter._csvEscape(count),
          Exporter._csvEscape(accountNames)
        ].join(','));
      });
    }

    // Grand total row
    if (summaryData && summaryData.grandTotal != null) {
      lines.push([
        this._csvEscape('25'),
        this._csvEscape('Total functional expenses'),
        this._csvEscape(this._formatCurrency(summaryData.grandTotal)),
        this._csvEscape(''),
        this._csvEscape('')
      ].join(','));
    }

    const csvContent = lines.join('\n');
    const filename = '990-part-ix-mapping-' + this._fileDate() + '.csv';
    this._triggerDownload(csvContent, filename, 'text/csv;charset=utf-8;');
  },

  /**
   * Generate and download an XLSX file with Part IX mapping data.
   * Requires SheetJS (XLSX global) to be loaded.
   */
  generateExcel(summaryData, mappingResults) {
    if (typeof XLSX === 'undefined') {
      alert('Excel export requires SheetJS library. Please ensure it is loaded.');
      return;
    }

    const wb = XLSX.utils.book_new();
    const date = this._displayDate();

    // --- Sheet 1: Part IX Summary ---
    const summaryRows = [];
    summaryRows.push(['Form 990 Part IX Mapping']);
    summaryRows.push(['Generated by 990 Mapper (szubair22.github.io/990Mapper) - ' + date]);
    summaryRows.push([]);
    summaryRows.push(['Line #', 'Description', 'Total Amount', '# Accounts']);

    if (summaryData && summaryData.lines) {
      summaryData.lines.forEach(function(item) {
        const total = (item.total != null) ? item.total : 0;
        const count = (item.count != null && item.count > 0) ? item.count : '';
        summaryRows.push([
          item.line,
          item.label,
          total,
          count
        ]);
      });
    }

    // Grand total row
    if (summaryData && summaryData.grandTotal != null) {
      summaryRows.push([
        '25',
        'Total functional expenses',
        summaryData.grandTotal,
        ''
      ]);
    }

    const ws1 = XLSX.utils.aoa_to_sheet(summaryRows);

    // Set column widths
    ws1['!cols'] = [
      { wch: 8 },   // Line #
      { wch: 50 },  // Description
      { wch: 18 },  // Total Amount
      { wch: 12 }   // # Accounts
    ];

    // Merge title row across all columns
    ws1['!merges'] = [
      { s: { r: 0, c: 0 }, e: { r: 0, c: 3 } },
      { s: { r: 1, c: 0 }, e: { r: 1, c: 3 } }
    ];

    // Format amount cells as currency (column C, starting at row 5)
    var dataStartRow = 4; // 0-indexed: row 1=title, 2=subtitle, 3=blank, 4=headers, 5+=data
    var totalRows = summaryRows.length;
    for (var r = dataStartRow; r < totalRows; r++) {
      var cellRef = XLSX.utils.encode_cell({ r: r, c: 2 });
      if (ws1[cellRef] && typeof ws1[cellRef].v === 'number') {
        ws1[cellRef].z = '$#,##0.00';
      }
    }

    XLSX.utils.book_append_sheet(wb, ws1, 'Part IX Summary');

    // --- Sheet 2: Account Detail ---
    const detailRows = [];
    detailRows.push(['Account Name', 'Account Number', 'Balance', 'Mapped to Line #', 'Line Description', 'Confidence']);

    if (mappingResults && mappingResults.length > 0) {
      mappingResults.forEach(function(result) {
        var linNum = result.line || result.lineNumber || '';
        var linDesc = result.lineDescription || result.label || '';
        var confidence = result.confidence || result.score || '';

        if (typeof confidence === 'number') {
          confidence = Math.round(confidence * 100) + '%';
        }

        detailRows.push([
          result.accountName || result.name || '',
          result.accountNumber || result.number || '',
          result.balance || result.amount || 0,
          linNum,
          linDesc,
          confidence
        ]);
      });
    } else if (summaryData && summaryData.lines) {
      // Fall back to building detail from summaryData
      summaryData.lines.forEach(function(item) {
        if (item.accounts && item.accounts.length > 0) {
          item.accounts.forEach(function(acct) {
            detailRows.push([
              acct.accountName || '',
              acct.accountNumber || '',
              acct.balance || 0,
              item.line,
              item.label,
              ''
            ]);
          });
        }
      });
    }

    const ws2 = XLSX.utils.aoa_to_sheet(detailRows);

    ws2['!cols'] = [
      { wch: 35 },  // Account Name
      { wch: 15 },  // Account Number
      { wch: 16 },  // Balance
      { wch: 15 },  // Mapped to Line #
      { wch: 45 },  // Line Description
      { wch: 12 }   // Confidence
    ];

    // Format balance cells as currency (column C, starting at row 2)
    for (var r2 = 1; r2 < detailRows.length; r2++) {
      var cellRef2 = XLSX.utils.encode_cell({ r: r2, c: 2 });
      if (ws2[cellRef2] && typeof ws2[cellRef2].v === 'number') {
        ws2[cellRef2].z = '$#,##0.00';
      }
    }

    XLSX.utils.book_append_sheet(wb, ws2, 'Account Detail');

    // Trigger download
    var filename = '990-part-ix-mapping-' + this._fileDate() + '.xlsx';
    XLSX.writeFile(wb, filename);
  },

  /**
   * Open a new browser window with a clean, printable Part IX worksheet.
   */
  openPrintView(summaryData, mappingResults) {
    var date = this._displayDate();
    var self = this;

    // Build the summary table rows
    var summaryTableRows = '';
    if (summaryData && summaryData.lines) {
      summaryData.lines.forEach(function(item) {
        var total = (item.total != null) ? self._formatCurrency(item.total) : '$0.00';
        summaryTableRows += '<tr>' +
          '<td class="line-num">' + self._htmlEscape(String(item.line)) + '</td>' +
          '<td>' + self._htmlEscape(item.label) + '</td>' +
          '<td class="amount">' + self._htmlEscape(total) + '</td>' +
          '</tr>\n';
      });
    }

    // Grand total row
    var grandTotalFormatted = (summaryData && summaryData.grandTotal != null)
      ? this._formatCurrency(summaryData.grandTotal)
      : '$0.00';

    // Build the account detail section
    var detailHtml = '';
    if (summaryData && summaryData.lines) {
      summaryData.lines.forEach(function(item) {
        if (item.accounts && item.accounts.length > 0) {
          detailHtml += '<div class="detail-group">';
          detailHtml += '<h3>Line ' + self._htmlEscape(String(item.line)) + ' - ' + self._htmlEscape(item.label) + '</h3>';
          detailHtml += '<table class="detail-table"><thead><tr>' +
            '<th>Account Name</th><th>Account Number</th><th>Balance</th>' +
            '</tr></thead><tbody>';
          item.accounts.forEach(function(acct) {
            detailHtml += '<tr>' +
              '<td>' + self._htmlEscape(acct.accountName || '') + '</td>' +
              '<td>' + self._htmlEscape(acct.accountNumber || '') + '</td>' +
              '<td class="amount">' + self._htmlEscape(self._formatCurrency(acct.balance)) + '</td>' +
              '</tr>';
          });
          detailHtml += '</tbody></table></div>';
        }
      });
    }

    var html = '<!DOCTYPE html>\n' +
      '<html lang="en">\n' +
      '<head>\n' +
      '<meta charset="UTF-8">\n' +
      '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n' +
      '<title>Form 990 Part IX - Mapping Worksheet</title>\n' +
      '<style>\n' +
      '@page {\n' +
      '  margin: 0.75in;\n' +
      '  size: letter;\n' +
      '}\n' +
      '\n' +
      '* {\n' +
      '  box-sizing: border-box;\n' +
      '}\n' +
      '\n' +
      'body {\n' +
      '  font-family: Georgia, "Times New Roman", Times, serif;\n' +
      '  font-size: 11pt;\n' +
      '  color: #222;\n' +
      '  max-width: 800px;\n' +
      '  margin: 0 auto;\n' +
      '  padding: 20px;\n' +
      '  line-height: 1.4;\n' +
      '}\n' +
      '\n' +
      'h1 {\n' +
      '  font-size: 16pt;\n' +
      '  text-align: center;\n' +
      '  margin-bottom: 4px;\n' +
      '  border-bottom: 2px solid #333;\n' +
      '  padding-bottom: 8px;\n' +
      '}\n' +
      '\n' +
      'h2 {\n' +
      '  font-size: 12pt;\n' +
      '  text-align: center;\n' +
      '  color: #555;\n' +
      '  font-weight: normal;\n' +
      '  margin-top: 4px;\n' +
      '  margin-bottom: 20px;\n' +
      '}\n' +
      '\n' +
      'h3 {\n' +
      '  font-size: 11pt;\n' +
      '  margin: 12px 0 6px 0;\n' +
      '  color: #333;\n' +
      '}\n' +
      '\n' +
      '.section-title {\n' +
      '  font-size: 13pt;\n' +
      '  font-weight: bold;\n' +
      '  margin-top: 30px;\n' +
      '  margin-bottom: 10px;\n' +
      '  border-bottom: 1px solid #999;\n' +
      '  padding-bottom: 4px;\n' +
      '  page-break-before: auto;\n' +
      '}\n' +
      '\n' +
      'table {\n' +
      '  width: 100%;\n' +
      '  border-collapse: collapse;\n' +
      '  margin-bottom: 16px;\n' +
      '}\n' +
      '\n' +
      'th, td {\n' +
      '  border: 1px solid #bbb;\n' +
      '  padding: 5px 8px;\n' +
      '  text-align: left;\n' +
      '  font-size: 10pt;\n' +
      '}\n' +
      '\n' +
      'thead th {\n' +
      '  background-color: #e8e8e8;\n' +
      '  font-weight: bold;\n' +
      '  font-size: 10pt;\n' +
      '}\n' +
      '\n' +
      '.line-num {\n' +
      '  text-align: center;\n' +
      '  width: 50px;\n' +
      '}\n' +
      '\n' +
      '.amount {\n' +
      '  text-align: right;\n' +
      '  font-family: "Courier New", Courier, monospace;\n' +
      '  white-space: nowrap;\n' +
      '}\n' +
      '\n' +
      '.total-row td {\n' +
      '  font-weight: bold;\n' +
      '  border-top: 2px solid #333;\n' +
      '}\n' +
      '\n' +
      '.detail-group {\n' +
      '  margin-bottom: 12px;\n' +
      '  page-break-inside: avoid;\n' +
      '}\n' +
      '\n' +
      '.detail-table {\n' +
      '  margin-left: 20px;\n' +
      '  width: calc(100% - 20px);\n' +
      '}\n' +
      '\n' +
      '.footer {\n' +
      '  margin-top: 30px;\n' +
      '  padding-top: 10px;\n' +
      '  border-top: 1px solid #999;\n' +
      '  font-size: 9pt;\n' +
      '  color: #666;\n' +
      '  text-align: center;\n' +
      '}\n' +
      '\n' +
      '@media print {\n' +
      '  body {\n' +
      '    padding: 0;\n' +
      '    max-width: none;\n' +
      '  }\n' +
      '\n' +
      '  thead th {\n' +
      '    background-color: transparent !important;\n' +
      '    -webkit-print-color-adjust: exact;\n' +
      '  }\n' +
      '\n' +
      '  .detail-group {\n' +
      '    page-break-inside: avoid;\n' +
      '  }\n' +
      '\n' +
      '  .section-title {\n' +
      '    page-break-after: avoid;\n' +
      '  }\n' +
      '\n' +
      '  .footer {\n' +
      '    position: fixed;\n' +
      '    bottom: 0;\n' +
      '    left: 0;\n' +
      '    right: 0;\n' +
      '  }\n' +
      '}\n' +
      '</style>\n' +
      '</head>\n' +
      '<body>\n' +
      '\n' +
      '<h1>Form 990 Part IX &mdash; Statement of Functional Expenses</h1>\n' +
      '<h2>Mapping Worksheet &mdash; Generated ' + this._htmlEscape(date) + '</h2>\n' +
      '\n' +
      '<table>\n' +
      '  <thead>\n' +
      '    <tr>\n' +
      '      <th class="line-num">Line #</th>\n' +
      '      <th>Description</th>\n' +
      '      <th class="amount" style="width:130px;">(A) Total</th>\n' +
      '    </tr>\n' +
      '  </thead>\n' +
      '  <tbody>\n' +
      summaryTableRows +
      '    <tr class="total-row">\n' +
      '      <td class="line-num">25</td>\n' +
      '      <td>Total functional expenses</td>\n' +
      '      <td class="amount">' + this._htmlEscape(grandTotalFormatted) + '</td>\n' +
      '    </tr>\n' +
      '  </tbody>\n' +
      '</table>\n' +
      '\n' +
      (detailHtml ? '<div class="section-title">Account Detail</div>\n' + detailHtml : '') +
      '\n' +
      '<div class="footer">\n' +
      '  Generated by 990 Mapper (szubair22.github.io/990Mapper) | This is a mapping aid, not tax advice.\n' +
      '</div>\n' +
      '\n' +
      '<script>\n' +
      '  setTimeout(function() { window.print(); }, 500);\n' +
      '</script>\n' +
      '\n' +
      '</body>\n' +
      '</html>';

    var printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
    } else {
      alert('Unable to open print view. Please allow pop-ups for this site.');
    }
  },

  /**
   * Escape HTML special characters.
   */
  _htmlEscape(str) {
    if (str == null) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }
};
